#!/usr/bin/env bash
# installs nginx on web-01 = listening on port 80

# update package list
sudo apt-get -y update
sudo apt-get -y upgrade

# installing of nginx
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

# modify default Nginx configuration to return 'Hello World!'
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'

# Restart Nginx without using systemctl
sudo service nginx restart
