#!/usr/bin/env bash
# Displays FizzBuzz when the number is a multiple of 3 and 5
#+ Displays Fizz when the number is multiple of 3
#+ Displays Buzz when the number is a multiple of 5

for i in {1..100};do
	three=$((i%3))
	five=$((i%5))

	if [ $five -eq 0 ] && [ $three -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $three -eq 0 ]
	then
                echo "Buzz"
	elif [ $five -eq 0 ]
	then
                echo "Fizz"
        else
		echo "$i"
	fi	
done
