#!/usr/bin/env bash
# loops 10 times and Displays "bad luck"(1-4), 'good luck' loop 8 and Best school for other.

i=1
while [ $i -le 10 ];do
	if [ $i -eq 4 ];then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$(( i + 1 ))
done
